#!/usr/bin/env php
<?php
require __DIR__ . '/shared.php';
require __DIR__ . '/app/Libraries/vendor/autoload.php';


use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;


abstract class Wizard extends Command
{
}

$Wizard = new Application();
$Wizard->add(new \System\Commands\MVC\ScaffoldCommand());
$Wizard->add(new \System\Commands\Database\DatabaseCommand());
$Wizard->add(new \System\Commands\Composer\ComposerCommand());
$Wizard->add(new \System\Commands\System\LogCommand());
$Wizard->add(new \System\Commands\System\GulpCommand());
$Wizard->run();
